#!/usr/bin/env python3
"""Compile a PRIVATE plaintext denylist into the committed digest file.

The denylist is never committed in plaintext. This tool turns a private list into
salted SHA-256 digests, which is what `scripts/check_client_data.py` reads.

  Private source (NEVER in the repo):  ~/.config/transilience/client-denylist.txt
  Output (never committed; path from $CLIENT_DENYLIST):  client-denylist.sha256

Usage:
  python3 scripts/gen_denylist.py                       # read the default private path
  python3 scripts/gen_denylist.py --in /path/list.txt   # or an explicit path
  printf 'acme\\nfoo corp\\n' | python3 scripts/gen_denylist.py --in -

Source format: one name per line, `#` comments and blank lines ignored. Names may
contain spaces ("acme bank") or dots ("acme.io"); both are normalised the same
way the checker normalises file content, so either spelling matches.

LIMITATION, stated plainly: hashing resists casual reading, not a determined
attacker. Anyone with a company-name wordlist can test membership offline. The
salt raises that cost and stops the file being a copy-pasteable roster; it is not
encryption. Treat the digest file as "not a directory of our clients", not as a
secret.
"""
from __future__ import annotations

import argparse
import hashlib
import os
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.environ.get("CLIENT_DENYLIST") or os.path.expanduser(
    "~/.config/transilience/client-denylist.sha256")
DEFAULT_SRC = os.path.expanduser("~/.config/transilience/client-denylist.txt")

# Fixed, published salt: it is a domain separator, not a secret (a secret salt
# could not live in a public repo anyway). It stops these digests being looked up
# in a generic precomputed rainbow table of company names.
SALT = b"transilience-communitytools-denylist-v1:"


def normalise(token: str) -> str:
    """Lowercase and collapse whitespace so 'Acme Bank' == 'acme bank'."""
    return " ".join(token.lower().split())


def digest(token: str) -> str:
    return hashlib.sha256(SALT + normalise(token).encode()).hexdigest()


def variants(name: str) -> set[str]:
    """A multi-word name is matched either spaced or joined ('acme bank'/'acmebank')."""
    n = normalise(name)
    out = {n}
    if " " in n:
        out.add(n.replace(" ", ""))
    return out


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--in", dest="src", default=DEFAULT_SRC,
                    help=f"plaintext source, or '-' for stdin (default: {DEFAULT_SRC})")
    args = ap.parse_args()

    if args.src == "-":
        raw = sys.stdin.read()
    else:
        if not os.path.exists(args.src):
            print(f"gen_denylist: no plaintext source at {args.src}\n"
                  f"Create it (one client name per line) OUTSIDE the repo, then re-run.",
                  file=sys.stderr)
            return 1
        with open(args.src, encoding="utf-8") as fh:
            raw = fh.read()

    names = [ln.strip() for ln in raw.splitlines()
             if ln.strip() and not ln.strip().startswith("#")]
    if not names:
        print("gen_denylist: source contained no names", file=sys.stderr)
        return 1

    digests = sorted({digest(v) for n in names for v in variants(n)})

    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write(
            "# Salted SHA-256 digests of client/engagement identifiers.\n"
            "# Generated by scripts/gen_denylist.py from a PRIVATE plaintext list that is\n"
            "# deliberately NOT in this repository. Enforced by scripts/check_client_data.py.\n"
            "#\n"
            "# Plaintext is not stored here on purpose: the roster of an offensive-security\n"
            "# firm's clients is itself sensitive. Digests resist casual reading, not an\n"
            "# offline dictionary attack -- see gen_denylist.py for the full caveat.\n"
            "#\n"
            "# To add an entry: append to the private list and re-run gen_denylist.py. Keep\n"
            "# this file OUT of the repository — supply it to CI via a secret and locally\n"
            "# via $CLIENT_DENYLIST.\n")
        for d in digests:
            fh.write(d + "\n")

    print(f"gen_denylist: wrote {len(digests)} digests from {len(names)} names -> "
          f"{os.path.relpath(OUT, REPO)}")
    print("Plaintext was NOT written to the repository.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
